# Generated by Django 4.1.2 on 2022-10-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_description_salesorder_descriptions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder",
            old_name="amount",
            new_name="amounts",
        ),
    ]
