# Generated by Django 4.1.2 on 2022-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_amount_salesorder_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="color",
            field=models.CharField(default="default title", max_length=255),
            preserve_default=False,
        ),
    ]
