# Generated by Django 4.1.2 on 2022-10-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_salesorder_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder",
            old_name="amounts",
            new_name="amount",
        ),
    ]
