# Generated by Django 4.1.2 on 2022-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("orders", "0006_rename_amounts_salesorder_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="product",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
